[constants]
a = 5
b = 3
result = "?[a b sort()]"
pi = 3.14159
radius = 5

[formulas]
circumference = "?[radius pi * 2 *]"

[sensors]
types = ["temperature", "humidity", "pressure"]
interval = 60

[network]
ip = "192.168.0.1"
timeout = 300

[database]
host = "localhost"
port = 5432

[logging]
level = "debug"